
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Staff36/config-repo-for-wom-wear
          default-label: main
          clone-on-start: true

#eureka:
#  client:
#    service-url:
#      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

#      jwt:
#        secret: 71d1edd38fcf979690d07b2b840d98547d57ac2c79a45bc3218fb4d50